#!/bin/bash
python main.py --inductive --ratio 0.0 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 0.0 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 0.0 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 0.0 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 0.0 --partially_inductive --inductive_edges 4
python main.py --inductive --ratio 0.2 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 0.2 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 0.2 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 0.2 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 0.2 --partially_inductive --inductive_edges 4
python main.py --inductive --ratio 0.4 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 0.4 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 0.4 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 0.4 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 0.4 --partially_inductive --inductive_edges 4
python main.py --inductive --ratio 0.6 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 0.6 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 0.6 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 0.6 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 0.6 --partially_inductive --inductive_edges 4
python main.py --inductive --ratio 0.8 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 0.8 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 0.8 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 0.8 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 0.8 --partially_inductive --inductive_edges 4
python main.py --inductive --ratio 1.0 --partially_inductive --inductive_edges 0
python main.py --inductive --ratio 1.0 --partially_inductive --inductive_edges 1
python main.py --inductive --ratio 1.0 --partially_inductive --inductive_edges 2
python main.py --inductive --ratio 1.0 --partially_inductive --inductive_edges 3
python main.py --inductive --ratio 1.0 --partially_inductive --inductive_edges 4